import SwiftUI
import CoreText

/// Manages custom font registration for the app
/// Call FontManager.registerFonts() at app startup to load Poppins and Crimson Pro
enum FontManager {

    /// Register all custom fonts from the Resources/Fonts directory
    static func registerFonts() {
        let fontNames = [
            "Poppins-Regular.ttf",
            "Poppins-Medium.ttf",
            "Poppins-SemiBold.ttf",
            "Poppins-Bold.ttf",
            "CrimsonPro-Regular.ttf",
            "CrimsonPro-Variable.ttf"
        ]

        for fontName in fontNames {
            registerFont(filename: fontName)
        }

        #if DEBUG
        // Print all registered fonts to verify they loaded
        print("📝 Registered custom fonts:")
        listAvailableFonts()
        #endif
    }

    /// Register a single font file
    private static func registerFont(filename: String) {
        // Use Bundle.module which is automatically generated by SPM for targets with resources
        let bundle = Bundle.module
        
        // Note: Bundle.module.url(forResource:...) expects the filename WITHOUT extension if using the older API,
        // but usually we pass extension separately.
        // However, the FontManager logic below splits it.
        
        let fontName = filename.replacingOccurrences(of: ".ttf", with: "")
        
        // Try to find the font in the module bundle
        guard let fontURL = bundle.url(forResource: fontName, withExtension: "ttf") else {
            print("⚠️ Could not find font file: \(filename)")
            print("   Bundle path: \(bundle.bundlePath)")
            return
        }

        registerFontFromURL(fontURL, filename: filename)
    }

    /// Register font from URL
    private static func registerFontFromURL(_ url: URL, filename: String) {
        var error: Unmanaged<CFError>?

        guard CTFontManagerRegisterFontsForURL(url as CFURL, .process, &error) else {
            if let error = error?.takeRetainedValue() {
                // kCTFontManagerErrorAlreadyRegistered = 105
                let nsError = error as Error as NSError
                if nsError.code != 105 {
                    print("⚠️ Failed to register font \(filename): \(error)")
                }
            }
            return
        }

        print("✅ Registered font: \(filename)")
    }

    /// List all available fonts (debug helper)
    private static func listAvailableFonts() {
        let available = NSFontManager.shared.availableFonts
        let poppins = available.filter { $0.contains("Poppins") }
        let crimson = available.filter { $0.contains("Crimson") }

        if !poppins.isEmpty {
            print("   Poppins variants:", poppins.joined(separator: ", "))
        } else {
            print("   ⚠️ No Poppins fonts found in system!")
        }
        
        if !crimson.isEmpty {
            print("   Crimson variants:", crimson.joined(separator: ", "))
        } else {
            print("   ⚠️ No Crimson fonts found in system!")
        }
    }
}
