name: Test Build

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Test server start
      run: |
        timeout 10s npm start || true
        echo "Server start test completed"

    - name: Verify Electron files
      run: |
        echo "Checking required files exist:"
        test -f electron-main-ipc.js && echo "✓ electron-main-ipc.js exists"
        test -f preload.js && echo "✓ preload.js exists"
        test -f server.js && echo "✓ server.js exists"
        test -d public && echo "✓ public directory exists"
        test -f public/index.html && echo "✓ index.html exists"
        test -f public/app-electron.js && echo "✓ app-electron.js exists"